Game logic
RoodzFernando/Tic-Tac-Toe-project pull request #3
Opened 2019-12-02 20:37 UTC by luis-novoa

We finished coding the game logic and we wait for feedback.

2019-12-02 21:20 UTC, ebukaume requested changes
## Changes Required! :stop_sign: 

Hi @luis-novoa  and @RoodzFernando :wave: 

Good job so far, but there are a few issues we need to address.

- [ ] You are expected to have at least 2 classes. _Usually, three: Game, Board and Player._
![pathwright ref](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone3/classes.png)
- [ ] All classes are kept in `lib` directory.
![pathwright ref](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone1/lib_dir_exist.png)
- [ ] The code should respect the single responsibility rule. You `bin/main` file is doing too much.
![ref](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone3/single_responsibility.png)

_See below for more :point_down:_ 

**Kindly submit another code review request after making the changes**

Happy Coding :v: 
**Ebuka Umeokonkwo**
 [Github](https://github.com/ebukaume) | [Linkedin](https://www.linkedin.com/in/ebukaume) | [Slack](https://app.slack.com/team/UFDKXE68L) | [Twitter](https://twitter.com/ebukaume)

2019-12-02 21:20 UTC, ebukaume commented on bin/main
> +
This method is way too long.

2019-12-03 17:16 UTC, imhta requested changes
# Require changes 🛑 

### Hello @luis-novoa @RoodzFernando , 👋   you have done a good job but still there function which is too large. Try to reduce that. Because it is not good practice. reference to that code below.

---
#### Don't forgot to request for another code review 
---
**Pon Muthu Selvam N**
_If you have any queries, feel free to ping me on slack_

2019-12-03 17:16 UTC, imhta commented on bin/main
**Try to minimize the length of the function. (because it is too large)**

2019-12-03 20:07 UTC, RoodzFernando commented
We minimized the length of the new_game method.

2019-12-03 21:05 UTC, shshamim63 commented
## Status :recycle: [!! Required Changes !!] :recycle: 
___
Hi @luis-novoa  and @RoodzFernando :wave,
Nice job :clap:. You have covered all the changes asked by the previous reviewer. That is awesome. But I have noticed some other issues. And I am sure that you will cover them easily :sunglasses: .
___
##### Please follow the instructions below :point_down:  to complete this project.
___
### :spades:  [Mandatory Changes] :spades: 
___
1. You have to move the pointed code from board class. Cause only the main should be responsible for rendering all the output.
https://github.com/RoodzFernando/Tic-Tac-Toe-project/blob/aed994ea5662fce9d3b5e2bc6b07b5fed2744ec2/lib/board.rb#L9-L17
![image1](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone3/only_main_print.png)
2. You have declared attr_accessor :board. So to access it you don't need that @board anymore.  
https://github.com/RoodzFernando/Tic-Tac-Toe-project/blob/aed994ea5662fce9d3b5e2bc6b07b5fed2744ec2/lib/board.rb#L19-L25
___
### Please fix the above mentioned issue and send another review request.
___
## :herb: Happy Coding :herb: 
### Shakhawat Hossain
[Linkedin](https://www.linkedin.com/in/shakhawathossainshamim/) | [Slack](Shakhawat Hossain)

2019-12-03 22:06 UTC, Forison requested changes
### Changes Required🛑
# Hi team👏,
I tried to run your app but kept getting an error🤔,
```require': cannot load such file -- ./lib/board (LoadError)``` is suspect module importation is problematic  
For the sake of your next submission make sure you 
* [ ] The application does not not allow a player to move into an occupied position.
* [ ] The application does not exit due to invalid input - it informs player about it and asks for their move again.
* [ ] The application can determine if move is a winning move
* [ ] The application can tell if there was a draw after players move
* [ ] The application can change active player
### Kindly get it to run on your local machine and test the requirements I have sent and submit for another review

#### Happy coding
Addo Boakye Forison

2019-12-03 23:31 UTC, Redvanisation approved these changes
# Milestone approved ✔️ 

### Hello team 🌟 

### _Nice work on this project, it seems that you have met the requirements so I am approving your project. 👍_ 

### You may merge to master and submit a project completion form. 🚀 

### Good luck! 🍀

2019-12-04 15:26 UTC, merged